INSERT OR IGNORE INTO tag_vocabulary(
    name, normalized_name, slug, description, status, created_at, updated_at
)
VALUES
    ('AI', 'ai', 'ai', 'AI 与智能系统', 'active', datetime('now'), datetime('now')),
    ('AI Engineering', 'ai engineering', 'ai-engineering', 'AI 工程化与应用落地', 'active', datetime('now'), datetime('now')),
    ('LLM', 'llm', 'llm', '大语言模型', 'active', datetime('now'), datetime('now')),
    ('Agent', 'agent', 'agent', 'AI Agent 与智能体系统', 'active', datetime('now'), datetime('now')),
    ('RAG', 'rag', 'rag', '检索增强生成', 'active', datetime('now'), datetime('now')),
    ('Prompt Engineering', 'prompt engineering', 'prompt-engineering', 'Prompt 设计与上下文工程', 'active', datetime('now'), datetime('now')),
    ('Machine Learning', 'machine learning', 'machine-learning', '机器学习', 'active', datetime('now'), datetime('now')),
    ('Deep Learning', 'deep learning', 'deep-learning', '深度学习', 'active', datetime('now'), datetime('now')),
    ('NLP', 'nlp', 'nlp', '自然语言处理', 'active', datetime('now'), datetime('now')),
    ('Computer Vision', 'computer vision', 'computer-vision', '计算机视觉', 'active', datetime('now'), datetime('now')),
    ('Recommendation System', 'recommendation system', 'recommendation-system', '推荐系统', 'active', datetime('now'), datetime('now')),
    ('MLOps', 'mlops', 'mlops', '机器学习工程与模型运维', 'active', datetime('now'), datetime('now')),
    ('AI Safety', 'ai safety', 'ai-safety', 'AI 安全、对齐与风险治理', 'active', datetime('now'), datetime('now')),
    ('Engineering', 'engineering', 'engineering', '工程实践与软件工程', 'active', datetime('now'), datetime('now')),
    ('Architecture', 'architecture', 'architecture', '架构设计与架构权衡', 'active', datetime('now'), datetime('now')),
    ('System Design', 'system design', 'system-design', '系统设计', 'active', datetime('now'), datetime('now')),
    ('Software Design', 'software design', 'software-design', '软件设计与设计原则', 'active', datetime('now'), datetime('now')),
    ('Backend', 'backend', 'backend', '后端工程', 'active', datetime('now'), datetime('now')),
    ('Frontend', 'frontend', 'frontend', '前端工程', 'active', datetime('now'), datetime('now')),
    ('Mobile', 'mobile', 'mobile', '移动端工程', 'active', datetime('now'), datetime('now')),
    ('Web', 'web', 'web', 'Web 技术与 Web 平台', 'active', datetime('now'), datetime('now')),
    ('API Design', 'api design', 'api-design', 'API 设计与接口治理', 'active', datetime('now'), datetime('now')),
    ('Microservices', 'microservices', 'microservices', '微服务架构', 'active', datetime('now'), datetime('now')),
    ('Distributed Systems', 'distributed systems', 'distributed-systems', '分布式系统', 'active', datetime('now'), datetime('now')),
    ('Computer Systems', 'computer systems', 'computer-systems', '计算机系统', 'active', datetime('now'), datetime('now')),
    ('Operating Systems', 'operating systems', 'operating-systems', '操作系统', 'active', datetime('now'), datetime('now')),
    ('Networking', 'networking', 'networking', '网络与协议', 'active', datetime('now'), datetime('now')),
    ('Storage Systems', 'storage systems', 'storage-systems', '存储系统', 'active', datetime('now'), datetime('now')),
    ('Database', 'database', 'database', '数据库', 'active', datetime('now'), datetime('now')),
    ('Query Optimizer', 'query optimizer', 'query-optimizer', '查询优化器', 'active', datetime('now'), datetime('now')),
    ('Cache', 'cache', 'cache', '缓存系统与缓存策略', 'active', datetime('now'), datetime('now')),
    ('Message Queue', 'message queue', 'message-queue', '消息队列与异步系统', 'active', datetime('now'), datetime('now')),
    ('Search', 'search', 'search', '搜索系统与检索技术', 'active', datetime('now'), datetime('now')),
    ('Data Engineering', 'data engineering', 'data-engineering', '数据工程', 'active', datetime('now'), datetime('now')),
    ('Data Pipeline', 'data pipeline', 'data-pipeline', '数据管道', 'active', datetime('now'), datetime('now')),
    ('Streaming', 'streaming', 'streaming', '流式计算与实时数据', 'active', datetime('now'), datetime('now')),
    ('Big Data', 'big data', 'big-data', '大数据系统', 'active', datetime('now'), datetime('now')),
    ('Data Warehouse', 'data warehouse', 'data-warehouse', '数据仓库与湖仓', 'active', datetime('now'), datetime('now')),
    ('Analytics', 'analytics', 'analytics', '分析系统与数据分析', 'active', datetime('now'), datetime('now')),
    ('Performance', 'performance', 'performance', '性能与性能优化', 'active', datetime('now'), datetime('now')),
    ('Scalability', 'scalability', 'scalability', '可扩展性', 'active', datetime('now'), datetime('now')),
    ('Reliability', 'reliability', 'reliability', '可靠性工程', 'active', datetime('now'), datetime('now')),
    ('High Availability', 'high availability', 'high-availability', '高可用架构', 'active', datetime('now'), datetime('now')),
    ('SRE', 'sre', 'sre', 'SRE 与生产系统运维', 'active', datetime('now'), datetime('now')),
    ('Observability', 'observability', 'observability', '可观测性', 'active', datetime('now'), datetime('now')),
    ('Monitoring', 'monitoring', 'monitoring', '监控、告警与诊断', 'active', datetime('now'), datetime('now')),
    ('Incident Review', 'incident review', 'incident-review', '故障复盘与事故分析', 'active', datetime('now'), datetime('now')),
    ('Testing', 'testing', 'testing', '测试与质量保障', 'active', datetime('now'), datetime('now')),
    ('Code Quality', 'code quality', 'code-quality', '代码质量与工程规范', 'active', datetime('now'), datetime('now')),
    ('Refactoring', 'refactoring', 'refactoring', '重构与演进式设计', 'active', datetime('now'), datetime('now')),
    ('CI/CD', 'ci/cd', 'ci-cd', '持续集成与持续交付', 'active', datetime('now'), datetime('now')),
    ('Infrastructure', 'infrastructure', 'infrastructure', '基础设施工程', 'active', datetime('now'), datetime('now')),
    ('Cloud Native', 'cloud native', 'cloud-native', '云原生技术', 'active', datetime('now'), datetime('now')),
    ('Kubernetes', 'kubernetes', 'kubernetes', 'Kubernetes 与容器编排', 'active', datetime('now'), datetime('now')),
    ('DevOps', 'devops', 'devops', 'DevOps 与工程交付流程', 'active', datetime('now'), datetime('now')),
    ('Platform Engineering', 'platform engineering', 'platform-engineering', '平台工程', 'active', datetime('now'), datetime('now')),
    ('Developer Tools', 'developer tools', 'developer-tools', '开发者工具', 'active', datetime('now'), datetime('now')),
    ('Engineering Productivity', 'engineering productivity', 'engineering-productivity', '工程效率', 'active', datetime('now'), datetime('now')),
    ('Open Source', 'open source', 'open-source', '开源项目与开源治理', 'active', datetime('now'), datetime('now')),
    ('Product Engineering', 'product engineering', 'product-engineering', '产品工程与业务系统工程', 'active', datetime('now'), datetime('now')),
    ('Security', 'security', 'security', '安全工程', 'active', datetime('now'), datetime('now')),
    ('Web Security', 'web security', 'web-security', 'Web 安全', 'active', datetime('now'), datetime('now')),
    ('AppSec', 'appsec', 'appsec', '应用安全', 'active', datetime('now'), datetime('now')),
    ('Cryptography', 'cryptography', 'cryptography', '密码学', 'active', datetime('now'), datetime('now')),
    ('Privacy', 'privacy', 'privacy', '隐私保护与隐私计算', 'active', datetime('now'), datetime('now')),
    ('Supply Chain Security', 'supply chain security', 'supply-chain-security', '软件供应链安全', 'active', datetime('now'), datetime('now')),
    ('Reverse Engineering', 'reverse engineering', 'reverse-engineering', '逆向工程', 'active', datetime('now'), datetime('now')),
    ('Programming Languages', 'programming languages', 'programming-languages', '编程语言', 'active', datetime('now'), datetime('now')),
    ('Compilers', 'compilers', 'compilers', '编译器', 'active', datetime('now'), datetime('now')),
    ('Runtime', 'runtime', 'runtime', '运行时系统', 'active', datetime('now'), datetime('now')),
    ('Algorithms', 'algorithms', 'algorithms', '算法', 'active', datetime('now'), datetime('now')),
    ('Theory', 'theory', 'theory', '理论计算机科学', 'active', datetime('now'), datetime('now')),
    ('Data Structures', 'data structures', 'data-structures', '数据结构', 'active', datetime('now'), datetime('now')),
    ('Computer Architecture', 'computer architecture', 'computer-architecture', '计算机体系结构', 'active', datetime('now'), datetime('now')),
    ('GPU', 'gpu', 'gpu', 'GPU 与异构计算', 'active', datetime('now'), datetime('now')),
    ('CUDA', 'cuda', 'cuda', 'CUDA 与 GPU 编程', 'active', datetime('now'), datetime('now')),
    ('HPC', 'hpc', 'hpc', '高性能计算', 'active', datetime('now'), datetime('now')),
    ('Embedded Systems', 'embedded systems', 'embedded-systems', '嵌入式系统', 'active', datetime('now'), datetime('now')),
    ('IoT', 'iot', 'iot', '物联网', 'active', datetime('now'), datetime('now')),
    ('Robotics', 'robotics', 'robotics', '机器人', 'active', datetime('now'), datetime('now')),
    ('Graphics', 'graphics', 'graphics', '图形学与可视化', 'active', datetime('now'), datetime('now')),
    ('HCI', 'hci', 'hci', '人机交互', 'active', datetime('now'), datetime('now')),
    ('Research', 'research', 'research', '计算机科研与研究议题', 'active', datetime('now'), datetime('now')),
    ('Paper Reading', 'paper reading', 'paper-reading', '论文阅读与论文解读', 'active', datetime('now'), datetime('now')),
    ('Research Method', 'research method', 'research-method', '科研方法与研究训练', 'active', datetime('now'), datetime('now')),
    ('Experiment', 'experiment', 'experiment', '实验设计与实验分析', 'active', datetime('now'), datetime('now')),
    ('Benchmark', 'benchmark', 'benchmark', '基准测试与评测体系', 'active', datetime('now'), datetime('now')),
    ('Reproducibility', 'reproducibility', 'reproducibility', '复现与可重复性', 'active', datetime('now'), datetime('now')),
    ('Learning Path', 'learning path', 'learning-path', '学习路线', 'active', datetime('now'), datetime('now')),
    ('CS Education', 'cs education', 'cs-education', '计算机教育与课程学习', 'active', datetime('now'), datetime('now')),
    ('Career', 'career', 'career', '技术职业发展', 'active', datetime('now'), datetime('now')),
    ('Interview', 'interview', 'interview', '面试与求职', 'active', datetime('now'), datetime('now')),
    ('Engineering Leadership', 'engineering leadership', 'engineering-leadership', '技术领导力', 'active', datetime('now'), datetime('now')),
    ('Engineering Culture', 'engineering culture', 'engineering-culture', '工程文化', 'active', datetime('now'), datetime('now')),
    ('Team Collaboration', 'team collaboration', 'team-collaboration', '团队协作', 'active', datetime('now'), datetime('now')),
    ('Productivity', 'productivity', 'productivity', '个人效率与工作流', 'active', datetime('now'), datetime('now')),
    ('Technical Writing', 'technical writing', 'technical-writing', '技术写作与知识整理', 'active', datetime('now'), datetime('now'));
